### ISSUE TITLE
[meta] Chainlink Hackathon Submission

### ISSUE THREAD

**Issue by gumdropsteve** [gumdropsteve/SmartRPA#14]
# Goal
> yeah forsure. if by the end of the hackathon we could get a proof of concept up and running on one of the test networks that would be really cool

**Deadline**: 11:59pm UTC (4:59pm PT) Sunday 11 April 2021 | https://chainlink-2021.devpost.com/

#### To Do...
- [ ] README.md
  - [ ] A project description (approximately 200 words)
  - [x] Diagram
  - [x] Clear & concise instructions on how to deploy project [for each individual part](https://youtu.be/mH0kBcfqLQA?t=827)
- [ ] 5-minute video demo
- [x] A link to GitHub/GitLab/code repository
- [x] A link to a working demo

# Details
## ELIGIBILITY
> - Teams must have no more than 5 hackers
> - No geographic restrictions on hackers
## REQUIREMENTS
> Submissions should include
> - A project description (approximately 200 words)
> - 5-minute video demo
> - A link to GitHub/GitLab/code repository
> - Optional: a link to a working demo
#### To qualify for the Chainlink Hackathon prizes
> - You must successfully use Chainlink oracles/price feeds, and the data fetched by the oracle must trigger a state change in the smart contract.
> - Your entry must abide by the overall hackathon rules.
> - While you may plan ahead of time, all code for your project must be written during the event.
> - You cannot steal another team’s source code, and you must certify that all code and presentations you submit are your own work.
> - For sponsorship prizes, to be eligible for their prizes you must use the technology mentioned in the prizes section. If you're unsure if you qualify, please reach out to their sponsorship channel in the [Discord](https://discord.com/invite/h3AvTHj).

> **For layer 1 prizes:**
> You must submit your project and a description on why the layer 1 you chose was the best. Also you can't just redeploy to multiple chains and submit to all. There must be a good reason to use the layer 1's you're using.

**Comment by gumdropsteve** [comment]
Good Submission Guidelines | Chainlink Hackathon Workshop
https://youtu.be/mH0kBcfqLQA

**Comment by gumdropsteve** [comment]
Example submission video: https://www.youtube.com/watch?v=1nnmgthdPqw

**Comment by gumdropsteve** [comment]
> Things left to do before the deadline:
> - [ ] fix smart contract unit tests
> - [ ] update home page video
> - [ ] update README/documentation
> - [ ] minor css/text changes 
> - [ ] deploy a fresh smart contract and fund it with enough chainlink for demos 
> - [ ] make sure the current contracts grid shows all relevant info 
> - anything I’m missing?
